services:
  - type: web
    name: E24
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn E24.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: E24.settings
