# Generated by Django 5.2.1 on 2025-05-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Runner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Lap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("laptime", models.DurationField(blank=True, null=True)),
                ("pace", models.CharField(blank=True, max_length=20, null=True)),
                ("total_time", models.DurationField(blank=True, null=True)),
                ("fixed", models.BooleanField(default=False)),
                (
                    "runner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="e24_app.runner",
                    ),
                ),
            ],
        ),
    ]
