# Generated by Django 5.2.1 on 2025-05-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e24_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lap",
            name="start_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
