# Generated by Django 5.2.1 on 2025-05-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e24_app", "0002_alter_lap_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lap",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
